### ISSUE TITLE
使用vue-router跳转页面返回的时候没有更新地址栏参数

### ISSUE THREAD

**Issue by 94ashui** [linxianxi/vue-use-sync-url#1]

**Comment by linxianxi** [comment]
你是怎么跳转的，代码发出来看看

**Comment by 94ashui** [comment]
> 你是怎么跳转的，代码发出来看看
用你项目里面的例子也是一样的。
example1页面 http://localhost:5174/example1?page=3
![image](https://user-images.githubusercontent.com/89236888/197923304-24900774-df00-494a-b1a2-332b0953e9e1.png)
然后切换到/example2页面
![image](https://user-images.githubusercontent.com/89236888/197923434-83c43384-82f7-454b-b8f9-77b071a33fca.png)
点浏览器回退到/example1页面
![image](https://user-images.githubusercontent.com/89236888/197923497-aaa985c6-4429-45c9-ab6f-385294521e68.png)

期望这个时候应该地址栏参数是保留的。

**Comment by linxianxi** [comment]
这个需求就不太正常，应该没见过这样的吧。要实现也是可以的，把参数保存到 localStorage，点击菜单路由跳转的时候带上就行了。文档下面有写如何保存

**Comment by 94ashui** [comment]
> 
这个不是和列表页面进详情然后从详情页面返回一样的场景么。

**Comment by linxianxi** [comment]
你这个是从一个菜单点击到另一个菜单，正常是不应该携带参数的。你随便在有这个功能的网站上试下就行了，比如 github issue 那个页面。你要做也是可以的，上面给了你方式

**Comment by linxianxi** [comment]
你说的这个是 vue-router 的 bug。我在 react 中没这个问题
